build:
  version: "3.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank-accounts-db # We use the same databases for dev, prod and default
    driverClassName:
    username: root
    password: root # NOT for production
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

accounts:
  message: "Bank accounts APIs "
  contactDetails:
    name: "Jan Doe - Support"
    email: "jan@bank.com"
  onCallSupport:
    - (089) 666-3216
    - (089) 666-3217
