build:
  version: "2.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bank-loans-db
    username: root
    password: root # NOT for production
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

loans:
  message: "Bank loans DEV APIs "
  contactDetails:
    name: "Ahmad - Non-prod Support"
    email: "ahmad@bank.com"
  onCallSupport:
    - (089) 666-3216
    - (089) 666-3217