build:
  version: "3.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bank-cards-db
    driverClassName:
    username: root
    password: root # NOT for production
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

cards:
  message: "Bank cards APIs "
  contactDetails:
    name: "Jan Doe - Support"
    email: "jan@bank.com"
  onCallSupport:
    - (089) 666-3216
    - (089) 666-3217