build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bank-cards-db
    driverClassName:
    username: root
    password: root # NOT for production
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

cards:
  message: "Bank cards PROD APIs"
  contactDetails:
    name: "Jan Doe - Support"
    email: "{cipher}732993bdb0eaca99dfba12b002d879f2a5f99558d873a528293a52358c6374f7"
  onCallSupport:
    - (089) 666-3216
    - (089) 666-3217
