build:
  version: "2.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank-accounts-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root # NOT for production
  jpa:
    show-sql: true
    sql:
      init:
        mode: always

accounts:
  message: "Bank accounts DEV APIs "
  contactDetails:
    name: "Ahmad - Non-prod Support"
    email: "ahmad@bank.com"
  onCallSupport:
    - (089) 666-3216
    - (089) 666-3217